apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - ingress.yml

configMapGenerator:
  - name: king-kudo-be-config
    literals:
      - AWS_KEY=foo
      - AWS_SECRET=bar
      - DYNAMODB_ENDPOINT=foobar
      - SLACK_SIGNING_SECRET=foo
      - SLACK_BOT_TOKEN=foo

commonLabels:
  app: king-kudo-be
